### ISSUE TITLE
Feature request: append instructions to circuit

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Stim#120]
I don't see any way to append a CircuitInstruction directly to a Circuit (working in the Python interface)

Use case: I want to separate out the code for the noiseless QEC circuit from the noise.  So I write the noiseless version.  Then I want to be able to iterate over the circuit and create a new circuit by appending the previous instructions plus new ones for noise (and dealing appropriately with repeat blocks).

**Comment by Strilanc** [comment]
I'll definitely add this next version.

A workaround in the meantime is to know the index `k` of operation as you're iterating (e.g. use `for k, op in enumerate(circuit)` and do `target += circuit[k:k+1]` to append the operation.

**Comment by Strilanc** [comment]
This will be in the next python release (no date atm).
