### ISSUE TITLE
Repetition code distance off by one

### ISSUE THREAD

**Issue by oscarhiggott** [quantumlib/Stim#122]
The X distance of a repetition code generated with `stim.Circuit.generated` is off by 1 (inputting distance d generates a distance d+1 repetition code).

E.g. rather than getting 2d-1 qubits I get:
```
>>> import stim
>>> stim.Circuit.generated("repetition_code:memory", distance=3, rounds=1).num_qubits
7
>>> stim.Circuit.generated("repetition_code:memory", distance=5, rounds=1).num_qubits
11
```

Looks like it could be fixed by subtracting one [here](https://github.com/quantumlib/Stim/blob/fde4de96d71961c7b6aad279c173f6cdc00c416b/src/gen/gen_rep_code.cc#L19).

**Comment by Strilanc** [comment]
Hahaha how did I miss that. Will fix for sure.

**Comment by oscarhiggott** [comment]
Great, thanks!

**Comment by Strilanc** [comment]
This will be in the next python release (no date atm).
