### ISSUE TITLE
Add support for randomly sampling Clifford circuits

### ISSUE THREAD

**Issue by QCmonk** [quantumlib/Stim#153]
A useful feature for this package (e.g. for something like simulating shadow tomography) would be to add functionality for randomly sampling Clifford circuits. 

If there is no obvious way of doing this a-priori with the code as it is now, I can have a go at implementing this myself - the procedure itself is not difficult though doing it in such a way that keeps up with Stims impressive scaling performance may require some time. 

Best,
QCmonk

**Comment by Strilanc** [comment]
Could you be more specific about what is being sampled? There is a method `stim.Tableau.random(n)` that selects a uniformly random n-qubit Clifford operation from the set of all possible Clifford operations of that size.

**Comment by QCmonk** [comment]
Ah! That is precisely what I was thinking - my fault for not reading the docs properly.

**Comment by QCmonk** [comment]
Apologies for resurrecting this @Strilanc but is there no way to convert a stim.Tableau object into a stim.TableauSimulator class? There seems to be a disconnect between the three modes of operation. I understand they each aim to fulfil a different purpose but they have different functionality that would be useful in the other classes. Namely there is no stim.TableauSimulator.random method which seems a bit strange.

**Comment by Strilanc** [comment]
You can use `stim.TableauSimulator.set_inverse_tableau(...)` to put a tableau into the tableau simulator.

(If you have the non-inverse tableau you can use `stim.Tableau.inverse()` or just `tableau**-1` to get the inverse.)

**Comment by QCmonk** [comment]
I see. That will certainly do the trick, thank you.
