### ISSUE TITLE
error installing stim under windows 10, python 3.8

### ISSUE THREAD

**Issue by qodesign** [quantumlib/Stim#154]
tried installing using pip -install stim --user
got this error message :  

building 'stim' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I'll try to install these, but I prefer not to. I have mingwin installed already

**Comment by Strilanc** [comment]
I will add this to the "reasons to figure out proper prebuilding of wheels" pile.
