### ISSUE TITLE
Bug in len?

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Stim#157]
The code
```
c = stim.Circuit()
c.append_operation("CNOT", [0, 1])
c.append_operation("CNOT", [2, 1])
print(len(c))
```
prints out 1 instead of 2?  Actually any number of CNOTs in a row like this seems to not count them?

**Comment by Strilanc** [comment]
This is because of automatic fusion of the instructions. If you print the circuit you'll see `CNOT 0 1 2 1` which is considered to be one instruction. If you access `c[0]` you will get that one instruction with the four targets. And `c[1] is nothing.
