### ISSUE TITLE
Save and load stim tableaus

### ISSUE THREAD

**Issue by iarayad** [quantumlib/Stim#163]
It would be cool if it was possible to save and load stim tableaus. 
I am interested in using a list of stim tableaus that I append to a circuit as gates. However, producing these gates requires external packages that I do not want to rely on anymore. Fortunately, the list of tableaus is always the same, so I want to save the list to directly load tableaus and use later.
I tried saving a tableau using `pickle.dump`, but I get `TypeError: cannot pickle 'stim.Tableau' object`. Is there a way to save and load stim tableaus?

**Comment by Strilanc** [comment]
You can use `repr(tableau)` to get a valid python expression evaluating to the tableau. You can save that string and `eval` it later with stim imported as a janky way of serializing the tableau. Using `eval` isn't a great idea for security reasons, but then again neither is using pickle.

Pybind11 does allow me to add pickle support... I'll look into doing it for next version.

**Comment by iarayad** [comment]
Thank you! this works well.
