### ISSUE TITLE
Stim package cannot run properly on PyCharm

### ISSUE THREAD

**Issue by Oblak13** [quantumlib/Stim#20]
Install the stim package as required and import it. But it cannot run properly on PyCharm. The result is "ImportError: PauliString: PyType_Ready failed (UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 46-47: invalid continuation byte)!"
![issue](https://user-images.githubusercontent.com/59550854/113144317-b0c23c80-925f-11eb-9fb8-df627c17fa19.png)

**Comment by Strilanc** [comment]
Whoah, that's really strange. I need more information to debug this.

What version of python are you using?
What operating system are you using?
How did you install stim? Just `pip install stim` from pycharm's terminal?

**Comment by Strilanc** [comment]
Also, does this only fail in stim version 1.2.*? Did it work in 1.0 and 1.1?

**Comment by Oblak13** [comment]
> Whoah, that's really strange. I need more information to debug this. Most likely something to do with using a unicode character in a `__doc__` string, which _should_ be fine.
> 
> What version of python are you using?
> What operating system are you using?
> How did you install stim? Just `pip install stim` from pycharm's terminal?



> Whoah, that's really strange. I need more information to debug this. Most likely something to do with using a unicode character in a `__doc__` string, which _should_ be fine.
> 
> What version of python are you using?
> What operating system are you using?
> How did you install stim? Just `pip install stim` from pycharm's terminal

>Yeah，it's really strange. 
>The Python version I'm using is 3.8.1 and I use Window10. 
>I install stim just `pip install stim` from pycharm's terminal. 
>Excuse me, what's wrong with that?

**Comment by Oblak13** [comment]
Yeah，it's&nbsp;really&nbsp;strange.
The&nbsp;Python&nbsp;version&nbsp;I'm&nbsp;using&nbsp;is&nbsp;3.8.1&nbsp;and&nbsp;I&nbsp;use&nbsp;Window10.
I&nbsp;install&nbsp;stim&nbsp;just&nbsp;pip&nbsp;install&nbsp;stim&nbsp;from&nbsp;pycharm's&nbsp;terminal.
Excuse&nbsp;me,&nbsp;what's&nbsp;wrong&nbsp;with&nbsp;that?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quantumlib/Stim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上11:55
***@***.***&gt;;
抄送:&nbsp;"Maple ***@***.******@***.***&gt;;
主题:&nbsp;Re: [quantumlib/Stim] Stim package cannot run properly on PyCharm (#20)





 
Whoah, that's really strange. I need more information to debug this.
 
What version of python are you using?
 What operating system are you using?
 How did you install stim? Just pip install stim from pycharm's terminal?

**Comment by Oblak13** [comment]
Yeah，it's really strange.
The Python version I'm using is 3.8.1 and I use Window10.
I install stim just pip install stim from pycharm's terminal.
Excuse me, what's wrong with that?

**Comment by Oblak13** [comment]
> Also, does this only fail in stim version 1.2.*? Did it work in 1.0 and 1.1?

I tried all versions of stim on pycharm, and only version 1.0 was successful.

**Comment by Oblak13** [comment]
I seem to know what the problem is. I successfully import Stim under Ubuntu system. Can PyCharm use Stim in a Windows 10

**Comment by Strilanc** [comment]
I think the issue is that I'm not declaring the docstrings in C++ as being UTF8, but I use unicode characters. I'll put together a test version with the docstrings annotated appropriately and hand it along to you to try.

**Comment by Oblak13** [comment]
That would be great. Thank you very much.

**Comment by Strilanc** [comment]
@Oblak13 Here is a package with hopefully fixed encoding. Let me know if it works.

[stim-1.2.dev0.tar.gz](https://github.com/quantumlib/Stim/files/6261563/stim-1.2.dev0.tar.gz)

**Comment by Oblak13** [comment]
@Strilanc I ran a test. The stim package was successfully installed on PyCharm and passed. Now I can compile the quantum stabilizer circuits normally. I really appreciate your help.

**Comment by Oblak13** [comment]
@Strilanc I ran a test. The stim package was successfully installed on PyCharm and passed. Now I can compile the quantum stabilizer circuits normally. I really appreciate your help.

**Comment by Strilanc** [comment]
Thanks for the fast test! (Sorry I took so long; have been on vacation.)

I'll make a release with this fix in the next few days.
