### ISSUE TITLE
Stim detector of opposite parity

### ISSUE THREAD

**Issue by newmanmg** [quantumlib/Stim#204]
Is it possible to declare detectors of _opposite_ parity to a set of measurements.  E.g. a detection event when some measurement is 0 instead of 1.  I would imagine a command like

`DETECTOR rec[-1] 1` or
`OPPOSITE_DETECTOR rec[-1]`?

Of course, this could be circumvented by adding a noiseless 1-measurement and comparing against that, but its less elegant.  Seems peculiar that one can add a trivially off detector, but not a trivially on detector.  Wondering if this functionality already exists somehow or could be easily added.

**Comment by Strilanc** [comment]
Detectors already handle the "parity is expected to be odd" case automatically. The expected parity is computed automatically in order to make comparisons. For example this produces a 10% detection fraction instead of a 90% detection fraction:

X 0
X_ERROR(0.1) 0
M 0
DETECTOR rec[-1]
