### ISSUE TITLE
Should Cirq translation of REPEAT set use_repetition_ids=False? 

### ISSUE THREAD

**Issue by daxfohl** [quantumlib/Stim#224]
In https://github.com/quantumlib/Stim/blob/429282441a9bb68269bb8bce7a78a9f581f07ac6/glue/cirq/stimcirq/_stim_to_cirq.py#L124

We now have an option to ditch the repetition ids that get prepended to each measurement key. To my understanding, that should better reflect the Stim circuit. https://github.com/quantumlib/Cirq/pull/4997

**Comment by daxfohl** [comment]
Also looks like ClassicallyControlledOperation isn't used yet?

**Comment by Strilanc** [comment]
Makes sense to use this. It's in a released version of cirq now?

**Comment by Strilanc** [comment]
Currently blocked on https://github.com/quantumlib/Cirq/issues/5418

**Comment by daxfohl** [comment]
The blocking issue was fixed by https://github.com/quantumlib/Cirq/pull/5419
