### ISSUE TITLE
Install Stim through anaconda

### ISSUE THREAD

**Issue by jisutich** [quantumlib/Stim#228]
Hi, 

Is it possible to install stim through anaconda? I tried it but it showed that the package is not found.

**Comment by Strilanc** [comment]
I think you can install pip via conda and then install pypi packages (such as stim) via pip. See: https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment/43729857#43729857

Let me know if that works.

**Comment by jisutich** [comment]
Yes, it works. I have successfully installed Stim. Thanks
