### ISSUE TITLE
Can't install on apple M1 silicon?

### ISSUE THREAD

**Issue by yuvalqm** [quantumlib/Stim#230]
Hi,

So I am trying to pip install on a macbook pro with an apple M1 chip and get this error:

> Building wheels for collected packages: stim
  Building wheel for stim (pyproject.toml) ... error
  error: subprocess-exited-with-error
  × Building wheel for stim (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'stim._stim_march_polyfill' extension
      src/stim.cc:17:10: fatal error: 'stim.h' file not found
      #include "stim.h"
               ^~~~~~~~
      1 error generated.
      /private/var/folders/l3/248nvdzs4qq77_56fkzmf9mr0000gp/T/pip-build-env-in57sore/overlay/lib/python3.8/site-packages/setuptools/_distutils/extension.py:131: UserWarning: Unknown Extension options: 'headers'
        warnings.warn(msg)
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for stim
Failed to build stim
ERROR: Could not build wheels for stim, which is required to install pyproject.toml-based projects

does it happen because of the chip or is it something else?

also using python 3.8.9 and latest pip

**Comment by Strilanc** [comment]
Should fixed it 1.9.dev1649881693 (try `pip install stim==1.9.dev1649881693`). Once 1.9 is out it'll be the automatic choice.

**Comment by yuvalqm** [comment]
thanks! at the end it worked with regular pip install but inside a conda environment instead of pyenv
