### ISSUE TITLE
stimcirq: Single pauli string channels with identity in string throws error.

### ISSUE THREAD

**Issue by dkafri** [quantumlib/Stim#231]
I'm looking at lines 345-347 (function `_stim_append_random_gate_channel`) of _cirq_to_stim.py. If the cirq.DensePauliString gate has a trivial index (i.e. identity) for one of the qubits, we get an error `TypeError: 'NoneType' object is not callable`
I suggest changing line 346 to

`pauli_targets = [target_p[p](t) for t, p in zip(t, g.sub_gate.pauli_mask) if p]`

**Comment by Strilanc** [comment]
@dkafri could you give a cirq circuit that actually fails to convert so I have something to test against?

**Comment by dkafri** [comment]
```python
import cirq
import stimcirq

q0, q1 = cirq.LineQubit.range(2)

op = cirq.RandomGateChannel(
    sub_gate=cirq.DensePauliString((0, 1)), # IX
    probability=0.2).on(q0, q1)
circuit = cirq.Circuit(op)

stimcirq.cirq_circuit_to_stim_circuit(circuit)
```
