### ISSUE TITLE
Add pipelined correlated reweighting

### ISSUE THREAD

**Issue by inmzhang** [quantumlib/Stim#243]
The reweighting method described in this [paper](http://arxiv.org/abs/2205.09828) seems can be integrated with stim quite well. Would you consider adding the reweighting option to stim in the future?

**Comment by Strilanc** [comment]
I don't think this makes sense as a feature of Stim. It's certainly *possible* to implement code that takes a DEM and the detection events from a shot and outputs a reweighted DEM, but it wouldn't be fast enough.

In order for a method like that to be fast, it has to be applied directly to the internal representation of the decoder. If the reweighting was implemented in Stim, then that would require the decoder to convert the DEM (into whatever the decoder's internal representation of the match graph is) **once per shot**. That is really expensive! Too expensive to put on the hot path of batch sampling or streaming.
