### ISSUE TITLE
MPP behaves differently in stim 1.9 vs earlier versions

### ISSUE THREAD

**Issue by qodesign** [quantumlib/Stim#289]
could not attach .py file so a simple test is a python script that shows the behavior :

circuit 1 works, but it's measuring 8 stabilizers of weight 2 each. result :
[[False False False False  True  True  True  True]
 [False False False  True False  True  True False]
 [ True  True  True  True  True  True  True  True]
 [False False  True False  True False  True False]
 [False False False False False False  True  True]
 [False False  True  True False False False False]
 [ True  True False  True False  True  True False]
 [ True  True  True False False  True False  True]]

circuit2 measures 4 stabilizers each of weight 4. 
This used to work in a previous version of stim (maybe a year old?). Now the results are always "False":
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]

import stim

# circuit1 works
circuit1=stim.Circuit('''
 R 0 1 2 3
 RX 4
 H 0
 CX 0 4
 CZ 0 4
 H 1
 CX 1 4
 H 2
 CZ 2 0 2 1
 CX 2 4
 H 3
 CZ 3 0 3 2
 CX 3 4
 CZ 3 4
 MPP Y0*Z1 Z3*Y4 X1*Z2 Z3*X4 Z0*Z1 X2*X4 Z0*Z2 Y3*Y4
 ''')

sampler = circuit1.compile_sampler()
print(sampler.sample(shots=8))

# circuit2 doesn't  works; used to work in earlier verion of stim

circuit2=stim.Circuit('''
 R 0 1 2 3
 RX 4
 H 0
 CX 0 4
 CZ 0 4
 H 1
 CX 1 4
 H 2
 CZ 2 0 2 1
 CX 2 4
 H 3
 CZ 3 0 3 2
 CX 3 4
 CZ 3 4
 MPP Y0*Z1*Z3*Y4 X1*Z2*Z3*X4 Z0*Z1*X2*X4 Z0*Z2*Y3*Y4
 ''')

sampler = circuit2.compile_sampler()
print(sampler.sample(shots=8))

**Comment by Strilanc** [comment]
Use triple-ticks (```) to start and end code blocks.

It's not clear to me what you think is broken here. You've said what they *are* returning but not what you think they *should* be returning. To me it looks like they're doing the correct thing.

You're saying that circuit1 is fine, but `circuit2` *shouldn't* be returning all false? What should it return?

**Comment by qodesign** [comment]
I just realized an embarrassing mistake : the all "False" *is* the correct behavior.
What's being measured in circuit2 are all stabilizers of the code and what's being prepared is in the codespace.
Sorry about that...you can go ahead and close this issue.
