### ISSUE TITLE
Expose `stim.FrameSimulator` to python API

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Stim#306]
It would be useful if the stim python API exposed a `stim.FrameSimulator` class that provided access to the underlying C++ `stim::FrameSimulator`, in the same way that `stim.TableauSimulator` exposes `stim::TableauSimulator`. Basically, copy-paste `src/stim/simulators/tableau_simulator.pybind.cc` to `src/stim/simulators/frame_simulator.pybind.cc` and then edit the details so apply to the frame simulator instead of the tableau simulator.

The main distinctions between the frame simulator, and the tableau simulator, are:

1. Absolute measurements -> measurement flips. The frame simulator doesn't report measurement results, it reports whether measurement results are flipped. Instead of tracking stabilizer generators it tracks error propagation.
2. Batching. The frame simulator works on hundreds or thousands of samples at a time, instead of one sample at a time. This is core to what makes it fast. There's a sense in which the frame simulator *can't* run 1 simulation... but it can run 256 simulations and discard 255 of them.
3. Cost. All gates, including measurement, are O(1) in the frame simulator.

From the perspective of the user, the frame simulator should have the following state:

1. A seeded random number generator.
2. A list of pauli strings, which each pauli string storing the current errors for one of the shots in the batch.
3. A list of measurement flip records, each storing whether measurements have been flipped. These records are append-only, with instructions like `M` make these records longer.
4. A list of detection event records, each storing whether detection events triggered in each shot or not. These records are append-only, with instructions like `DETECTOR` make these records longer.
5. A list of accumulating observable records, each storing whether observables have been flipped so far in each shot or not. Instructions like `OBSERVABLE_INCLUDE` cause these records to update.

Here is an attempt at writing down what the API should be:

```
class FrameSimulator:
    def __init__(self, *, batch_size: int, seed: Optional[int] = None)
    def copy(self, *, copy_rng: bool = False, seed: Optional[int] = None)

    def do(self, obj: Union[stim.Circuit, stim.CircuitInstruction, stim.CircuitRepeatBlock, stim.PauliString, stim.Tableau], *, targets: Optional[List[int]] = None) -> None

    def get_measurement_record() -> np.ndarray
    def get_current_errors() -> List[stim.PauliString]
    def get_detection_event_record() -> np.ndarray
    def get_observable_flip_record() -> np.ndarray

    def set_measurement_record(self, vals: np.ndarray) -> None
    def set_detection_event_record(self, vals: np.ndarray) -> None
    def set_observable_flip_record(self, vals: np.ndarray) -> None)
    def set_current_errors(self, errors: List[stim.PauliString])

    # utility methods
    def peek_x_flipped(self, qubit: int) -> np.ndarray
    def peek_y_flipped(self, qubit: int) -> np.ndarray
    def peek_z_flipped(self, qubit: int) -> np.ndarray
    def peek_obs_flipped(self, val: stim.PauliString) -> np.ndarray
    def measure_obs(self, val: stim.PauliString) -> np.ndarray

    # per-gate methods like in tableau simulator
    def H(self, *targets) -> None
    def CX(self, *targets) -> None
    ...
    def measure(self, *targets, basis: str = 'Z') -> np.ndarray  # 1 axis for batch, 1 axis for targets
```

**Comment by danielbarter** [comment]
Now I understand why pauli noise can be run independently from a tableau simulation, gonna implement this

**Comment by fdmalone** [comment]
Is there anything blocking this? If not I can have a go. Seems like a useful issue to search the code.

**Comment by fdmalone** [comment]
Ok cool, this sounds sort of therapeutic so I'd be happy to be assigned.

**Comment by ababar-usc** [comment]
@fdmalone, are you working on this right now? I am working on something where'd I like this feature so I offered to pick this up (https://quantumcomputing.stackexchange.com/questions/32350/stim-peek-or-extract-circuit-pauli-frame) but happy to let you take charge if you've already started on this (but would appreciate being kept in the loop in that case though, thank you)

**Comment by fdmalone** [comment]
I probably won't get to it for a week or so, so if you want to take over then go for it!

**Comment by fdmalone** [comment]
@ababar-usc after a long hiatus I'm ready to start working on this again unless you've gotten it done in the mean time?

**Comment by ababar-usc** [comment]
@fdmalone, I did, but I got sidetracked to finish up another project:/ You can pick it up but happy to help in any way I can.
