### ISSUE TITLE
Add `stim.PauliString.{to,from}_tableau`

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Stim#309]

**Comment by danielbarter** [comment]
Hi @Strilanc: I would like to implement this. `pauliString -> tableau` seems pretty straightforward (Pauli group acts on itself via conjugation). What are you imagining for `tableau -> pauliString`

**Comment by danielbarter** [comment]
PR for C++ side of this: https://github.com/quantumlib/Stim/pull/339
