### ISSUE TITLE
Make `make install` install something

### ISSUE THREAD

**Issue by yurivict** [quantumlib/Stim#331]

**Comment by Strilanc** [comment]
Could you be more specific about what you are doing and what isn't happening?

**Comment by yurivict** [comment]
There is no 'install' make target. This is because there are no ```install``` instructions in CMakeLists.txt.

**Comment by Strilanc** [comment]
Oh, you mean like run a make command to install libstim as a library that can be linked to or to install stim as a command line tool in the system? I've just been building it and then adding the out directory to my PATH, or using the fact that the python package includes the command line tool.

**Comment by yurivict** [comment]
Library, headers. and possibly cmake and pkgconfig files.
