### ISSUE TITLE
Fix the '15 detector' limit on decomposing also applying when not decomposing errors

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Stim#332]
Error message says `An error case in a composite error exceeded that max supported number of symptoms`

This is only supposed to occur when `decompose_errors=True` is specified. It's limited because internally it converts the detectors affected by each of the error's possible Pauli products into bitmasks and then uses bitwise logic to understand how they mesh. When that isn't needed, it's sufficient to just compute the actual products without any bitmasking.

**Comment by ChrisPattison** [comment]
I just found myself running into this limitation for `decompose_errors=False` the other day. If this isn't on your list of things to do, I could start to look into preparing a PR?

**Comment by Strilanc** [comment]
That would be very helpful! Let me know if you have any troubles. That particular method is quite gnarly, but luckily the main goal is not to change the gnarly bits but to have an escape clause early on.
