### ISSUE TITLE
Separate python class and python method definitions for pybind

### ISSUE THREAD

**Issue by danielbarter** [quantumlib/Stim#341]
in `src/stim/py/stim.pybind.cc` there is the following comment:
```
    // CAUTION: The ordering of these is important!
    // If a class references another before it is registered, method signatures can get messed up.
    // For example, if DetectorErrorModel is defined after Circuit then Circuit.detector_error_model's return type is
    // described as `stim::DetectorErrorModel` instead of `stim.DetectorErrorModel`.
```
would it make sense to split all the pybind functions up into functions defining the python classes and functions defining the python methods, so that order no longer matters (other than all classes defined before all methods) This is already the case for some, but not all of the binding code. There is also some inconsistency between how things are named. We have `pybind_$TYPE_methods` and `pybind_$TYPE_after_types_all_defined`, but as far as I can tell, there isn't a semantic difference.

**Comment by Strilanc** [comment]
Yes, it would make sense to do this.

**Comment by danielbarter** [comment]
Do you have a preference for naming convention? I am leaning towards `pybind_$TYPE` and `pybind_$TYPE_methods`

**Comment by Strilanc** [comment]
Sounds good to me.

**Comment by danielbarter** [comment]
OK took a shot at this: https://github.com/quantumlib/Stim/pull/342

**Comment by Strilanc** [comment]
Fixed by https://github.com/quantumlib/Stim/pull/342
