### ISSUE TITLE
Add stim.Tableau.to_numpy/from_numpy and stim.PauliString.to_numpy/from_numpy

### ISSUE THREAD

**Issue by amirebrahimi** [quantumlib/Stim#355]
Currently, to rebuild the matrix from an instance of a `Tableau` it requires multiple calls to `.x_output()` and `.z_output()`. Would it be possible to have a call that would return all rows of x/z either as `PauliString` or in GF2 form?

**Comment by Strilanc** [comment]
I'm not sure I want to add this method. Typically I've added methods because it's complex to implement from python, or actually impossible to do from python because there's some time complexity advantage (e.g. the inverse output methods).

For this method it seems like the only benefit is it turns these two lines:

```
x_outs = [t.x_output(k) for k in range(len(t))]
z_outs = [t.z_output(k) for k in range(len(t))]
```

into one line like this

```
x_outs, z_outs = t.all_outputs()
```

But the original two lines aren't that complicated, and they're much clearer about the format of the result. Is there a benefit to this method besides making those two lines into one expression? This seems like it's not paying its weight in having-to-write-documentation.

Also, what is GF2 form?

**Comment by amirebrahimi** [comment]
> ```
> x_outs = [t.x_output(k) for k in range(len(t))]
> z_outs = [t.z_output(k) for k in range(len(t))]
> ```
> 
> into one line like this
> 
> ```
> x_outs, z_outs = t.all_outputs()
> ```
> 
> But the original two lines aren't that complicated, and they're much clearer about the format of the result. Is there a benefit to this method besides making those two lines into one expression? This seems like it's not paying its weight in having-to-write-documentation.

I'm in agreement with you if it were only about syntax. It's more about the overhead cost of the calls. I found that the following hack shaves off 1 ms, which is important to us because it is called in the innermost loop. I'm figuring that if we could get all outputs together that it would reduce this overhead and might even be better than below.

```
    lines = repr(tableau).split("\n")
    x_output = lines[2:2+n]
    z_output = lines[4+n:4+n+n]
```

> Also, what is GF2 form?

Binary symplectic matrix form

**Comment by Strilanc** [comment]
Could you describe more about what your innerloop is for? Maybe we can find a better place to make a cut to improve the performance.

Could you give an example of the GF2 form of a tableau? E.g. what's the GF2 for the CNOT?

**Comment by amirebrahimi** [comment]
Innermost loop is for calculating single qubit error spread.

Perhaps I'm not using standard terminology. Here's an example:
```
tableau_to_matrix_form(StimSupport.CX(0,1))
GF([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], order=2)
```

where `CX` is:
```
        T = Tableau(n)
        T.append(Tableau.from_named_gate("CNOT"), [i, j])
```

**Comment by amirebrahimi** [comment]
I'll give you a little more to work with. Initially I had:

```
    for i in range(n):
        xs = tableau.x_output(i)
        zs = tableau.z_output(i)
        
        for j in range(n):
             x = xs[j]
             z = zs[j]
             X_errors[j] += int(x in [1, 2] or z in [1, 2])
             Z_errors[j] += int(x > 1 or z > 1)
             Y_errors[j] += int(x in [1, 3] or z in [1, 3])
```

but this was too slow, so then I went to:

```
    for i in range(n):
        X_errors[i] = n - str(cliff.x_output(i)).count('_')
        Z_errors[i] = n - str(cliff.z_output(i)).count('_')
        Y_errors[i] = n - str(cliff.y_output(i)).count('_')
```

still too slow, so then I went to:
```
    lines = repr(cliff).split("\n")
    x_output = lines[2:2+n]
    z_output = lines[4+n:4+n+n]
    for i in range(n):
        x = str(x_output[i])
        z = str(z_output[i])
        X_errors[i] = n - x.count('_')
        Z_errors[i] = n - z.count('_')
        
        y_count = 0
        for j in range(1,n+1):  # skip the sign
            if x[j] == z[j]:
                y_count += 1
        Y_errors[i] = n - y_count
 ```

which is a bit of a hack

**Comment by Strilanc** [comment]
Ah, okay, you mean (roughly) the bit table format used in Scott Aaronson's paper. And it looks like it's not just the tableau getting in your way but also the pauli string.

I think it's reasonable to add a method to Tableau and to PauliString that serializes their contents into numpy arrays. Something like this:

```
>>> p = stim.PauliString("_XYZ_XYZ_XXX")
>>> p.to_numpy()
[[0 1 1 0   0 1 1 0  0 1 1 0  1 1 1],
 [0 0 1 1   0 0 1 1  0 0 1 1  0 0 0]] dtype=bool8
>>> p.to_numpy(bit_packed=True)
[[0x66 0x76],
 [0x33 0x03]] dtype=uint8
```

Note that's a 2d array with first axis "X vs Z" and second axis "qubit index".

The tableau method could be similar, except it would return a 4d array with first axis "input X vs Z", second axis "output X vs Z", third axis "input qubit index", fourth axis "output qubit index"? Maybe an option to flatten the XZ axes into the qubit axes since that's common? Would also need a way to get the signs out. And probably want reverse methods for going from numpy arrays back into the tableau/pauli string.

**Comment by amirebrahimi** [comment]
Sounds good to me. If you prefer to use the bit table format used in Aaronson's paper that would be okay, too. The reason why the format I showed above is column-oriented is somewhat arbitrary. Either way, if it is possible to get the full array I think this will help considerably.

**Comment by Strilanc** [comment]
@amirebrahimi Okay, here is the method I am going to implement:

```python
def to_numpy(
    self,
    *,
    bit_packed: bool = False
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Decomposes the contents of the tableau into six numpy arrays.
    
    The first four numpy arrays correspond to the four quadrants of the table defined
    in Aaronson and Gottesman's "Improved Simulation of Stabilizer Circuits"
    ( https://arxiv.org/abs/quant-ph/0406196 ).
    
    The last two numpy arrays are the X and Z sign bit vectors of the tableau.
    
    Args:
        bit_packed: Defaults to False. Determines whether the output numpy arrays
            use dtype=bool8 or dtype=uint8 with 8 bools packed into each byte.
    
    Returns:
        An (x2x, x2z, z2x, z2x, x_signs, z_signs) tuple encoding the tableau.
    
        x2x: A 2d table of whether or not tableau(X_i)_j is X or Y (instead of I or Z).
        x2z: A 2d table of whether or not tableau(X_i)_j is Z or Y (instead of I or X).
        z2x: A 2d table of whether or not tableau(Z_i)_j is X or Y (instead of I or Z).
        z2z: A 2d table of whether or not tableau(Z_i)_j is Z or Y (instead of I or X).
        x_signs: A vector of whether or not tableau(X_i) is negative.
        z_signs: A vector of whether or not tableau(Z_i) is negative.
    
        If bit_packed=False then:
            x2x.dtype=x2z.dtype=z2x.dtype=z2z.dtype=x_signs.dtype=z_signs.dtype = np.bool8
            x2x.shape=x2z.shape=z2x.shape=z2z.shape = (len(tableau), len(tableau))
            x_signs.shape=z_signs.shape = len(tableau)
            x2x[i, j] == tableau.x_output_pauli(i, j)] in [1, 2]
            x2z[i, j] == tableau.x_output_pauli(i, j)] in [2, 3]
            z2x[i, j] == tableau.z_output_pauli(i, j)] in [1, 2]
            z2z[i, j] == tableau.z_output_pauli(i, j)] in [2, 3]
    
        If bit_packed=True then:
            x2x.dtype=x2z.dtype=z2x.dtype=z2z.dtype=x_signs.dtype=z_signs.dtype = np.uint8
            x2x.shape=x2z.shape=z2x.shape=z2z.shape = (len(tableau), len(tableau))
            x_signs.shape=z_signs.shape = len(tableau)
            (x2x[i, j // 8] >> (j % 8)) & 1 == tableau.x_output_pauli(i, j)] in [1, 2]
            (x2z[i, j // 8] >> (j % 8)) & 1 == tableau.x_output_pauli(i, j)] in [2, 3]
            (z2x[i, j // 8] >> (j % 8)) & 1 == tableau.z_output_pauli(i, j)] in [1, 2]
            (z2z[i, j // 8] >> (j % 8)) & 1 == tableau.z_output_pauli(i, j)] in [2, 3]
    
    Examples:
        >>> import stim
        >>> t = stim.Tableau.from_conjugated_generators(
        ...     xs=[
        ...         stim.PauliString("-Y_ZY"),
        ...         stim.PauliString("-Y_YZ"),
        ...         stim.PauliString("-XXX_"),
        ...         stim.PauliString("+ZYX_"),
        ...     ],
        ...     zs=[
        ...         stim.PauliString("-_ZZX"),
        ...         stim.PauliString("+YZXZ"),
        ...         stim.PauliString("+XZ_X"),
        ...         stim.PauliString("-YYXX"),
        ...     ],
        ... )
    
        >>> x2x, x2z, z2x, z2z, x_signs, z_signs = t.to_numpy()
        >>> x2x
        array([[ True,  True,  True, False],
               [False, False,  True,  True],
               [False,  True,  True,  True],
               [ True, False, False, False]])
        >>> x2z
        array([[False,  True, False,  True],
               [False, False, False,  True],
               [ True,  True, False, False],
               [ True,  True, False, False]])
        >>> z2x
        array([[False,  True,  True,  True],
               [False, False, False,  True],
               [False,  True, False,  True],
               [ True, False,  True,  True]])
        >>> z2z
        array([[False,  True, False,  True],
               [ True,  True,  True,  True],
               [ True, False, False, False],
               [False,  True, False, False]])
        >>> x_signs
        array([ True,  True,  True, False])
        >>> z_signs
        array([ True, False, False,  True])
    
        x2x, x2z, z2x, z2z, x_signs, z_signs = t.to_numpy(bit_packed=True)
        >>> x2x
        array([[7],
               [12],
               [14],
               [1]])
        >>> x2z
        array([[10],
               [8],
               [3],
               [3]])
        >>> z2x
        array([[14],
               [8],
               [10],
               [13]])
        >>> z2z
        array([[10],
               [15],
               [1],
               [2]])
        >>> x_signs
        array([7], dtype=uint8)
        >>> z_signs
        array([9], dtype=uint8)
    """"
```

**Comment by Strilanc** [comment]
@amirebrahimi  This is now merged and available in the dev release `1.10.dev1663805381` (use `pip install stim==1.10.dev1663805381`).

Let me know if there are any issues, so they can be fixed before it gets into a stable release.

**Comment by amirebrahimi** [comment]
Thanks for making a dev release. I tried it out and while the method is useful for getting numpy arrays out it unfortunately isn't as performant as using the `repr` hack:

```
%%timeit
t = Tableau(8)
(x2x, x2z, z2x, z2z, x_signs, z_signs) = t.to_numpy()
36.1 µs ± 2.17 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

vs

```
%%timeit
t = Tableau(8)
lines = repr(t).split("\n")
x_output = lines[2:2+n]
z_output = lines[4+n:4+n+n]
12.4 µs ± 61.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

Any ideas how we could shave this time down?

**Comment by amirebrahimi** [comment]
Also one, small typo in the docs for `to_numpy`:

```
  Returns:
        An (x2x, x2z, z2x, **z2x**, x_signs, z_signs) tuple encoding the tableau.
```

**Comment by Strilanc** [comment]
Oh. I was imagining you were working with substantially larger tableaus. The optimizations I made are very helpful for those:

```
>>> t = stim.Tableau(800)

>>> %timeit repr(t).split("\n")
13.4 ms ± 408 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>>> %timeit t.to_numpy(bit_packed=True)
64.1 µs ± 6.24 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

For tiny tableaus all the overhead is going to be coming from python itself. I'm not sure how much I can do to make it faster than slicing the repr, because that does very few python operations. I'm tempted to recommend that you use the C++ API.

**Comment by amirebrahimi** [comment]
Yes, eventually will be working with much larger Tableaus, so that's good to know gains will come with those.

**Comment by Strilanc** [comment]
@amirebrahimi Okay, I looked more into how to return numpy arrays using pybind, and found out how to do it much more efficiently. Once https://github.com/quantumlib/Stim/pull/359 is merged the runtime of the method should improve 10x from 20-40us to ~2-4us.

**Comment by Strilanc** [comment]
@amirebrahimi give `pip install stim==1.10.dev1664114306` a try.

**Comment by amirebrahimi** [comment]
Rockin! Confirmed that this is super fast now.
