### ISSUE TITLE
Add arm64 wheels

### ISSUE THREAD

**Issue by oscarhiggott** [quantumlib/Stim#378]
Currently only x86_64 wheels are available for mac, so pip installing on Apple Silicon for a rosetta-emulated x86_64 version of python is fast, but pip installing for arm64 python requires building from source. So it would be nice if the following could be added to the `build_dist` matrix in the CI:

```
          {os: macos-latest, dist: cp38-macosx_arm64},
          {os: macos-latest, dist: cp39-macosx_arm64},
          {os: macos-latest, dist: cp310-macosx_arm64},
```

Admittedly there's no way to test them on github actions as they're cross-compiled on an x86_64 runner...but that's also true for the source distribution.

**Comment by Strilanc** [comment]
Fixed by https://github.com/quantumlib/Stim/commit/69854c66031ee52840891cf933da1e8e8d5496d4
