### ISSUE TITLE
Add `separate_observables` to `read_shot_data_file`

### ISSUE THREAD

**Issue by oscarhiggott** [quantumlib/Stim#408]
When reading shot data using `read_shot_data_file` and `bit_packed=True`, it's a bit inconvenient having to separate out the observables, since the end of the detector bits and beginning of the observable bits can be within the same byte (so simply using numpy array slicing doesn't do the job without some extra lines). Though perhaps I'm missing a trick here? Would be convenient if there was a `separate_observables=True` option so that detector bits and observable bits could more easily be split into separate numpy arrays.

**Comment by Strilanc** [comment]
Makes sense.

I have mixed feelings about this one since it's a case where the observables should already have been separated, but it's nice to allow incremental improvements.
