### ISSUE TITLE
More documentation for sweep bits

### ISSUE THREAD

**Issue by AdamWRichardson** [quantumlib/Stim#439]
There currently isn't much explaining what the sweep bit arguments are. From the docstrings that do exist it seems that it's a way to use classical data as the control for two qubit gates but I'm not sure if this is true.

Could there be more documentation about what sweep bits are and where they are valid and invalid please? For example it seems it's possible for the target of a two qubit gate to be a sweep bit.

I'm happy to contribute if I can but I think my assumptions need checking first!

**Comment by Strilanc** [comment]
@AdamWRichardson where did you initially look to find information on them? Could be useful to spread the information around more.

**Comment by AdamWRichardson** [comment]
I was originally reading through the [Python API](https://github.com/quantumlib/Stim/blob/main/doc/python_api_reference_vDev.md) where I first came across them and found:

> sweep_bits_filepath: Defaults to None. A file containing sweep data, or None. When specified, sweep data (used for `sweep[k]` controls in the circuit, which can vary from shot to shot) will be read from the given file. When not specified, all sweep bits default to False and no sweep-controlled operations occur

Which I didn't understand until finding the file format doc. I also just stumbled upon the [command line usage document](https://github.com/quantumlib/Stim/blob/main/doc/usage_command_line.md) which also adds some information.

I'm happy to add links to these other documents in the API if that helps others. Apologies for prematurely raising a ticket.
