### ISSUE TITLE
Probability to get error when implement `sinter.predict_observables` method in getting_start.ipynb

### ISSUE THREAD

**Issue by 282898474** [quantumlib/Stim#448]
When implement function `sinter.predict_observables` method in `count_logical_errors`
`predictions = sinter.predict_observables(
        dem=detector_error_model,
        dets=detection_events,
        decoder='pymatching',
    )`
Is probability to get a permission error, and there will be a new directory in ''C:\\Users\\UserName\\AppData\\Local\\Temp\\' which won't be deleted for each time error occurs. Usually, the probability of error is higher when `num_shots` is larger

`---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
File ~\.conda\envs\quantumion\lib\shutil.py:606, in _rmtree_unsafe(path, onerror)
    605 try:
--> 606     os.unlink(fullname)
    607 except OSError:

PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\UserName\\AppData\\Local\\Temp\\tmp823cixvn\\sinter_dets.b8'

**Comment by Strilanc** [comment]
Hm. The error is that another process is using the file? It looks like either the main process is starting to delete files before the worker process has been killed, or killing the working process is leaving the file in a permanently marked-as-in-use state.

This should be fixable, hopefully by just calling `join` on each subprocess when shutting down the workers.

**Comment by 282898474** [comment]
I didn't use multi-process, all I have done is repeat getting_start_ipynb, maybe there is a multi-process from the source code of package. And it is weird that it is probabilistic to get error. It seems that when the number of errors in quantum circuit exceeds some threshold, the process is killed.

**Comment by Strilanc** [comment]
sinter uses multiprocessing behind the scenes. It's likely probabilistic because it depends whether or not the child finishes being killed before the manager starts deleting its files.

**Comment by ucapgum** [comment]
I'm also getting the same error on Windows by just trying to run the code from the example notebook.

**Comment by Strilanc** [comment]
@282898474 can you verify if the linked pull request solves the issue?

To do so:

1. download the [zip file of wheels produced for the PR](https://github.com/quantumlib/Stim/suites/10184255422/artifacts/498315841)
2. unzip it
3. download and open the getting started notebook
4. `!pip install PATH_TO_THE_RIGHT_WHEEL_WITHIN_THE_EXTRACTED_FILES` (e.g. `stim-1.11.dev1672856345-cp39-cp39-win_amd64.whl` for 64 bit windows python 3.9)
5. Run the collect calls a few times to make sure they've stopped failing

**Comment by Strilanc** [comment]
Note: updated instructions for checking if it works to install sinter instead of stim

**Comment by Strilanc** [comment]
You can also install it by cloning the repo, pulling the branch from https://github.com/quantumlib/Stim/pull/452 , then `!pip install -e PATH_TO_REPO/glue/sample`.
