### ISSUE TITLE
How to correctly populate `simd_bit_table` when sampling via the C++ API

### ISSUE THREAD

**Issue by markturner289** [quantumlib/Stim#509]
This is a question about the memory layout of `stim::simd_bit_table` and how to correctly populate the table with samples via the C++ API.

I find that when I use `stim::detector_samples` the rows in the simd table alternate between being populated with some lit up detectors and rows that are completely blank. The code below reproduces this with all versions of libstim I tested:

```c++
#include "stim/circuit/circuit.h"
#include "stim/gen/gen_surface_code.h"
#include "stim/simulators/detection_simulator.h"

int main()
{
    stim::CircuitGenParameters circuit_params(1, 3, "rotated_memory_x");
    circuit_params.after_clifford_depolarization = 0.11;
    circuit_params.before_measure_flip_probability = 0.01;

    const auto circuit = stim::generate_surface_code_circuit(circuit_params).circuit;

    auto rng = std::mt19937_64();
    const size_t num_shots = 20;

    const stim::DetectorsAndObservables dets_obs(circuit);
    stim::simd_bit_table<stim::MAX_BITWORD_WIDTH> sample =
        stim::detector_samples(circuit, dets_obs, num_shots, false, true, rng);

    const size_t num_dets = dets_obs.detectors.size();

    // Adds some extra space below and to the right of the relevant area of the bit table
    std::cout << sample.str(num_dets * 3, num_shots + 5) << "\n\n";

    return 0;
}
```

The stdout then shows the following:

```
11.......1.11............
.........................
.1...11.1.1.11...111.....
.........................
.1..1...1.11..1.11.1.....
.........................
......11..11..1..........
.........................
.1..11.11.111...1..1.....
.........................
.1....1......111..1......
.........................
.....1.11....1...11......
.........................
..........11.111.........
.........................
1.....1.111.1.....1......
.........................
.........................
.........................
.........................
.........................
.........................
.........................
```

If I read this correctly, the first eight odd rows contain detector data and the ninth odd row is the observable. Please could you help me understand how I have managed to introduce this alternating horizontal pattern into the bit table? My sense is that I use the C++ API incorrectly because when I inspect the bit table [here](https://github.com/quantumlib/Stim/blob/838735edc3d62b834520209095c69ca605527ef0/src/stim/py/compiled_detector_sampler.pybind.cc#L42) while executing the following python code the simd bit table is densely packed. So,

```python
import stim
stim_circuit = stim.Circuit.generated(code_task="surface_code:rotated_memory_x",
                                      distance=3, rounds=1,
                                      after_clifford_depolarization=0.11,
                                      before_measure_flip_probability=0.01)
sampler = stim_circuit.compile_detector_sampler(seed=4)
detector_data, obs_data = sampler.sample(
    20, separate_observables=True, bit_packed=True)
```

yields,

```
.1.....1...1.............
.1.11..11.1..1.....1.....
.1..11.11.11....11.1.....
...1111...1........1.....
....11.1..11.1..1........
1.1.1..11...1......1.....
..1111.1..111...1..1.....
...1.1..1........1.......
.......1..1.1............
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
```

**Comment by Strilanc** [comment]
Well that's terrifying. Anything that can mess with the randomness of samples is a super critical bug, as it would compromise statistics like logical error rates that go into papers.

When I run your example code on my machine, there are no alternating rows. However, I notice that the results I get are the same as yours just without the rows...

```
11.......1.11............
.1...11.1.1.11...111.....
.1..1...1.11..1.11.1.....
......11..11..1..........
.1..11.11.111...1..1.....
.1....1......111..1......
.....1.11....1...11......
..........11.111.........
1.....1.111.1.....1......
...
```

I think I know what is going wrong, as I've actually run into it before. It's likely that libstim was built with `-march=native` which picked 256 bit AVX for the simd words while you built the code calling libstim without this flag which resulted in 128 bit SSE for the simd words. The really tricky thing here is that although the method you are calling does have a signature that says the size of the simd words, the mention is only in the return type, and return types aren't included in overload resolution or in the .so file... so the linker happily links your 128-bit-word expecting code to the 256-bit-word providing code in libstim. When I caught this the first time I started templating the simd words class to make this silent failure into a compile time failure, but it misses cases like return values as you've just experienced, and I haven't yet gone the further step of templating anything and everything that touches simd word to make this truly impossible to happen.

You can work around this issue by adding `-march=native` to your compile flags, or removing the march flag from the libstim target in stim's source code. Properly fixing it requires templating a rather large part of stim's source code.

**Comment by markturner289** [comment]
Thank you for the interesting and detailed explanation.

Adding the `-march=native` flag fixes the issue I reported. Further, I can confirm that, as you say, `stim::MAX_BITWORD_WIDTH` is set to 128 without the flag and 256 with the flag.

Do I understand you correctly that the longer term fix would involve turning functions such as `stim::simd_bit_table` into function templates so that something like this is possible in client code?

```C++
const auto sample = std::detector_samples<stim::MAX_BITWORD_WIDTH>(circuit, ....);
```

I would be happy to get involved in some of this work if that seems useful in future and aligns with the project's aims.

**Comment by Strilanc** [comment]
It's unfortunately a somewhat extensive change to make.

To template the method you called, you need to template the methods and classes that it uses (such as the pauli frame simulator).

To template the pauli frame simulator, you need to refactor the fact that stim stores a frame simulator function pointer for each gate. Presumably associating this data with the frame simulator itself, so that instantiating its template brings the needed function tables into being.

So this change spans all the way from the top (simulation method signatures) to the bottom (how gates are defined) of the library.

**Comment by Strilanc** [comment]
I'd be happy for someone to work on this, and it would be valuable to do (when this thing triggers a bug it's a serious failure and also very time consuming). Just... be aware of the scale of what you're getting into.

If you really want to do it, we could set up a meeting or etc to discuss it more. The C++ API in general is kinda terrible (a major reason I don't guarantee its compatibility across versions) and someone polishing off hard edges here and there would be nice.
