### ISSUE TITLE
Support for more complex circuits for the `before`/`after` functions

### ISSUE THREAD

**Issue by AlexBourassa** [quantumlib/Stim#514]
Thanks @Strilanc for teaching me how to use the PauliString and associated `before`/`after` function.  That will be super helpful.  

At the moment I can do something like this 

```python
sc = stim.Circuit("""
    CX 1 0
    CX 0 1
    S 0
    """
)
p=stim.PauliString('ZI')
p.after(sc)
```
However, as we discussed last time, it would be helpful if those function could also support more complex circuits such as ones with TICK instructions. Eg

```python
sc = stim.Circuit("""
    CX 1 0
    TICK
    CX 0 1
    S 0
    """
)
```

Or even with Annotations (which would just be ignored in this case).  Eg

```python
sc = stim.Circuit("""
    QUBIT_COORDS(0, 0) 0
    CX 1 0
    CX 0 1
    S 0
    """
)
```

**Comment by Strilanc** [comment]
Will do

**Comment by Strilanc** [comment]
Fixed by https://github.com/quantumlib/Stim/pull/516
