### ISSUE TITLE
Add `stim.reference_sample` method

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Stim#532]
Basically this just calls `TableauSimulator::reference_sample_circuit` and returns the result. It's a method that returns a consistent (within one version of stim) and valid sample from the circuit, ignoring all noise processes.

**Comment by fdmalone** [comment]
Am I right that this and #531 are connected in that you would like to be able to pass a reference_sample into Compiled(Measurement)Sampler.__init__?

**Comment by Strilanc** [comment]
@fdmalone Yes, that's right. Giving the user control over the reference sample enables emulation of some advanced use cases, where the reference sample is not consistent from shot to shot in circuits with controlled cliffords.
