### ISSUE TITLE
circuit.diagram('interactive')  doesn't work in jupyter notebook web interface

### ISSUE THREAD

**Issue by augustehirth** [quantumlib/Stim#557]
Running `stim.Circuit().diagram('interactive')` works in Google Colab, but doesn't seem to in the web environment provided by `jupyter notebook`. 

The following:
```
import stim
circuit = stim.Circuit('H 0')
circuit.diagram('interactive')
```

Yields the following in a localhosted jupyter notebook: 
![image](https://github.com/quantumlib/Stim/assets/45543029/4c4d1eb3-9926-493b-b6ce-abff5ccba3b1)

And yields the following in Google Colab.

![image](https://github.com/quantumlib/Stim/assets/45543029/9e9f9f31-3452-4b80-85e6-301912df0b01)

Versions:
Python 3.10.9
notebook==6.5.4
stim==1.11.0

**Comment by augustehirth** [comment]
Some followup information: 

Completing the following steps:
1. Replace line https://github.com/quantumlib/Stim/blob/b0f087007a58f4ed43a6fa090b2d50d6ad365e8e/dev/regen_crumble_to_cpp_string_write_to_stdout.sh#L16  with `        rollup glue/crumble/main.js | uglifyjs -c --toplevel;`
2. Regenerate [`src/stim/diagram/crumble_data.cc`](https://github.com/quantumlib/Stim/blob/b0f087007a58f4ed43a6fa090b2d50d6ad365e8e/src/stim/diagram/crumble_data.cc) with `sh dev/regen_crumble_to_cpp_string_write_to_stdout.sh`
3. Reinstall Stim using the rules from https://github.com/quantumlib/Stim/blob/b0f087007a58f4ed43a6fa090b2d50d6ad365e8e/src/stim/diagram/crumble_data.cc.

```
bazel build :stim_dev_wheel
pip uninstall stim --yes
pip install bazel-bin/stim-dev-py3-none-any.whl
```
4. Launch the same jupyter notebook used before
```
cd [notebook dir path]
jupyter notebook
```

Yields the following: 
1. Running the notebook for the first time yields the following view:
![image](https://github.com/quantumlib/Stim/assets/45543029/13e358be-0d6d-4e08-9610-a634d3780c57)

3. In this state, the hotkeys used by crumble are inconsistently intercepted. 
4. For example, clicking on an empty part of the menu bar and pressing `H` brings up Jupyter Notebook's hotkey panel, and ALSO highlights the `H` operation in crumble's gate-grid menu. 
5. However, clicking on a code or text cell to get a text cursor and pressing `H` fails to type the letter, and still highlights the `H` operation in crumble's menu.
6. If you click on one of the qubits in crumble's qubit grid, then click outside of the crumble interface, the qubit will still be highlighted. Pressing `H` will add the H gate to that qubit, even if the cursor is elsewhere.
7. Pressing `esc` fails to change the focus; the hotkey interception remains.
8. At this point, re-running the cells yields the original, blank crumble interface from the first post.
9. The hotkey interception issues persist after re-running the cells.  
10. In Google Chrome's inspect menu, the following error is available after re-running the cells.
![image](https://github.com/quantumlib/Stim/assets/45543029/285a088f-51dd-45f0-aff2-412117540406)
11. After re-running the cells to get an empty crumble interface, if you save and reload the page, you get back to the visible-crumble view from step 1 without having to run the code. 
12. The hotkey interception persists, and the inspect error is not present after reloading.

Other info:
1. The above behavior only occurs once the mangling from `uglifyjs` is removed. Without it, the result is always an empty-crumble interface, with the following error, no matter the tested combinations of re-running, saving, and reloading. 
![image](https://github.com/quantumlib/Stim/assets/45543029/a3252f89-9e4b-4374-b3a9-13872fdc6e9b)
2. The above behavior is the same if `uglifyjs` is removed entirely.
3. None of the above behaviors are visible on Google Colab, where crumble works as expected.
4. `Gate` is the first-defined variable in the `<script>` component of the HTML output of `crumble.diagram('interactive')`. 
5. There's a `Code cell is missing an id field` nbformat warning in the notebook console occasionally.

Hesitant conclusions/guesses:
1. Jupyter seems unhappy when the script is run again and re-declares the same variables. It may be necessary that this information is added to the notebook's `custom.js` file once, and then checked for in later runs. My guess is that colab doesn't support the notebook-scope javascript that base notebook does, and thus treats each run of the cell as a new instance. This works with crumble because all the relevant state is encoded in the circuit text, so reloading it yields the same configuration (minus things like the Show Import/Export window).
2. Colab is doing some explicit handling/interception of focus, perhaps by treating html cell outputs as iframes. In colab, crumble doesn't even know it has lost focus until it is clicked on again and the internal focus is updated.  In jupyter, it has access to and watches the whole webpage.
3. Putting crumble in some sort of wrapper, like it's own iframe or a widget as in [https://github.com/adgt/pyQuirk](pyQuirk), may work to instance both its javascript and focus for both normal notebooks and colab.

**Comment by Strilanc** [comment]
Ah, this is almost definitely the bug where Jupyter doesn't isolate HTML results into iframes. I probably need to do the isolation myself.

**Comment by augustehirth** [comment]
This seems to work pretty well to my first impression. 

I've done some very limited testing with an ugly fix that just wraps the whole thing in an iframe: https://github.com/augustehirth/Stim/commit/4924e3630c369f25477c3bd0d1b251ada805e675

Ways to get crumble to run in an iframe:
1. `IPython.display.HTML` provides the `metadata={'isolated':True}` option, which puts the result in an iframe. Crumble works here without intercepting hotkeys, but is vertically compacted. There may be a way to vertically expand the frame. 
![image](https://github.com/quantumlib/Stim/assets/45543029/0ea4f206-474c-4486-97cd-90dbf1fcf706)
2. Manually wrapping the html in an iframe and passing it to `IPython.display.HTML`  lets/forces you to choose a fixed size for the frame. This lets you make it bigger, but then it might have issues not automatically scaling on different devices. Ipython also gives you a warning because it wants you to use it's built in `IPython.display.IFrame`, which seems like a hilariously useless wrapper that actually removes functionality, notably the `srcdoc` field that supports inline html, which might be necessary here.
![image](https://github.com/quantumlib/Stim/assets/45543029/84d4f67a-4046-496d-9615-7e59f4759e6c)
3. You can however use `IPython.display.IFrame` to just... run a webpage via a url. Notably, the algassert-hosted version of crumble. Using this enables you to launch crumble already including marks, which is a great upside! However, using this in a useful manner requires a stim-circuit to crumble-circuit to crumble-url-circuit converter, which I haven't found in Stim yet. This method also requires fixed frame sizes.
![image](https://github.com/quantumlib/Stim/assets/45543029/7181ae91-1d1e-4a70-b7f5-e3d3d0836fba)
4. Which leads me to the "fix" from https://github.com/augustehirth/Stim/commit/4924e3630c369f25477c3bd0d1b251ada805e675 , where the html output of `circuit.diagram('interactive')` is wrapped in an iframe. Width and height are fixed as before, which causes the same scrolling unpleasantness. 
![image](https://github.com/quantumlib/Stim/assets/45543029/36da239a-b9cb-4be9-978c-03fc3041a99a)
5. The location of this "fix" is a little unnecessarily deep, affecting any html embedding of crumble, including the second use of `write_crumble_html_with_preloaded_circuit` at https://github.com/quantumlib/Stim/blob/b0f087007a58f4ed43a6fa090b2d50d6ad365e8e/src/stim/cmd/command_diagram.cc#L211, which is not the one used by `circuit.diagram('interactive')` (I think). However I did build it as a webserver from the [instructions](https://github.com/quantumlib/Stim/tree/b0f087007a58f4ed43a6fa090b2d50d6ad365e8e/glue/crumble#building-crumble) and it seemed ok.

**Comment by Strilanc** [comment]
Something to test out is trying this fix for the SVG viewer and the 3d model viewer, which also have this isolation issue. The 3d viewer actually works around it jankily, and I'd prefer if it was just iframe'd.

Getting it to work for the SVGs and the 3d models would also have the benefit of practicing on a simpler case.

**Comment by augustehirth** [comment]
This branch: https://github.com/quantumlib/Stim/compare/main...augustehirth:Stim:iframe_everything
puts SVG, GLTF and HTML type diagrams in an iframe when they pass through `_repr_html_`. 

It looks and works fine, but still requires manually fixing the width and height of the iframe at line: 
https://github.com/augustehirth/Stim/blob/1c98343e9657e04ee4f81b905bbefab9a9bd4a5a/src/stim/cmd/command_diagram.pybind.cc#L88

This might cause more issues with different shapes and such.
