### ISSUE TITLE
Canonical stabilizers are being truncated?

### ISSUE THREAD

**Issue by FalafelGood** [quantumlib/Stim#562]
I'm working with some fairly large circuits (~1000+ qubits), and I've noticed that stim.TableauSimulator.canonical_stabilizers() is truncating the PauliStrings at length 466. What can I do to read the canonical stabilizers out in full? For context, I am working from a Jupyter notebook.

Here's some code demonstrating the behavior:
```
circuit = stim.Circuit()
simulator = stim.TableauSimulator()
N = 467
circuit.append("H", range(N))
simulator.do(circuit)
stabs = simulator.canonical_stabilizers()
print(stabs[-1])
```

Expected output:
+___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________X

Actual Output:
+___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

**Comment by Strilanc** [comment]
This seems to be a deeper down bug related to inverting tableaus. Simplest repro I've managed is this one:

```
import stim
t = stim.Tableau(1) + stim.Tableau(466)
p = stim.PauliString(len(t))
p[1] = 'Z'
assert t.inverse().z_output(1) == p  # fails!
```

Very worrying; the fact the direct sum is needed suggests something to do with bounds checking within simd registers.

**Comment by Strilanc** [comment]
Okay, I've confirmed it also happens with just 64 bit values instead of fancy simd things. Also I've figured out where the 467 comes from: it's the first number such that floor(n*1.1) > 512. The 1.1 comes from various places that pad the tableau inside the tableau simulator by a constant factor to avoid quadratic costs when iterating towards big tableaus one by one.
