### ISSUE TITLE
Can pybind11 version be updated / relaxed?

### ISSUE THREAD

**Issue by tjni** [quantumlib/Stim#623]
Hello! I am working on packaging in [nixpkgs](https://github.com/NixOS/nixpkgs), and we have updated to pybind11 2.11.1. I am sorry I know nothing about pybind11. Is it a dependency whose version can be relaxed to support this?

**Comment by Strilanc** [comment]
Are you referring to the version declared in `WORKSPACE` (for the Bazel build) or in `pyproject.toml` (for the setup.py build)?

The Bazel one is quite hard to loosen because e.g. it declares a sha256 hash. The setup.py one can probably be changed from `==2.9.2` to `~=2.11`.

**Comment by tjni** [comment]
Thank you for the fast reply! I'm referring to the `pyproject.toml` one. If you don't mind, I can create a PR and we can see.

**Comment by Strilanc** [comment]
Go for it.
