### ISSUE TITLE
stimcirq.cirq_circuit_to_stim_circuit fails converting 2 qubit asymmetric depolarizing error channels.

### ISSUE THREAD

**Issue by nonohuff** [quantumlib/Stim#625]
Output:

```
File [stimcirq/_cirq_to_stim.py:93], in cirq_circuit_to_stim_circuit(circuit, qubit_to_index_dict)
     10 def cirq_circuit_to_stim_circuit(
     11     circuit: cirq.AbstractCircuit, *, qubit_to_index_dict: Optional[Dict[cirq.Qid, int]] = None
     12 ) -> stim.Circuit:
     13     """Converts a cirq circuit into an equivalent stim circuit.
     14 
     15     Not all circuits can be converted. In order for a circuit to be convertible, all of its operations must be
   (...)
     91             edit_circuit.append_operation("H", targets)
     92     """
---> 93     return cirq_circuit_to_stim_data(circuit, q2i=qubit_to_index_dict, flatten=False)[0]

File [stimcirq/_cirq_to_stim.py:114], in cirq_circuit_to_stim_data(circuit, q2i, flatten)
    111     elif isinstance(q, cirq.GridQubit):
    112         helper.out.append_operation("QUBIT_COORDS", [q2i[q]], [q.row, q.col])
--> 114 helper.process_moments(circuit)
    115 return helper.out, helper.key_out

File [stimcirq/_cirq_to_stim.py:440], in CirqToStimHelper.process_moments(self, moments)
    438 def process_moments(self, moments: Iterable[cirq.Moment]):
...
    173 if self._num_qubits != 1:
--> 174     raise ValueError('num_qubits should be 1')
    175 return self._error_probabilities.get('X', 0.0)

ValueError: num_qubits should be 1
```

stimcirq.cirq_circuit_to_stim_circuit fails converting 2 qubit

**Comment by Strilanc** [comment]
Could you provide the code that caused this exception? In my testing it seems to work:

```
import stim
import stimcirq

a = stimcirq.stim_circuit_to_cirq_circuit(stim.Circuit("""
    PAULI_CHANNEL_2(0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01) 0 1
"""))
print(a)
```

```
0: ───PauliMix(II:0.85,IX:0.01,IY:0.01,IZ:0.01,XI:0.01,XX:0.01,XY:0.01,XZ:0.01,YI:0.01,YX:0.01,YY:0.01,YZ:0.01,ZI:0.01,ZX:0.01,ZY:0.01,ZZ:0.01)───
      │
1: ───#2──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by nonohuff** [comment]
The issue is the other direction.
`my_circuit = cirq.Circuit(cirq.asymmetric_depolarize(error_probabilities={'II': 1, 'IX': 0, 'IY': 0, 'IZ': 0, 'XI': 0, 'XX': 0, 'XY': 0, 'XZ': 0, 'YI': 0, 'YX': 0, 'YY': 0, 'YZ': 0, 'ZI': 0, 'ZX': 0, 'ZY': 0, 'ZZ': 0}).on(cirq.LineQubit(0), cirq.LineQubit(1)))
print(my_circuit)
stimcirq.cirq_circuit_to_stim_circuit(my_circuit)`

**Comment by nonohuff** [comment]
Prints the cirq circuit, like so,
```
0: ───A(II:1, IX:0, IY:0, IZ:0, XI:0, XX:0, XY:0, XZ:0, YI:0, YX:0, YY:0, YZ:0, ZI:0, ZX:0, ZY:0, ZZ:0)───
      │
1: ───(1)─────────────────────────────────────────────────────────────────────────────────────────────────
```

 but then gives the error above

**Comment by nonohuff** [comment]
A note of this. Should be a relatively easy fix. [cirq.AsymmetricDepolarizingChannel](https://quantumai.google/reference/python/cirq/AsymmetricDepolarizingChannel#attributes) objects have an attribute, "error_probabilities", which returns a dictionary with their associated error probabilities. (e.g. {'I': 0.94, 'X': 0.01, 'Y': 0.02, 'Z': 0.03} or {'II': 0.8836, 'IX': 0.0094, 'IY': 0.0188, 'IZ': 0.0282, 'XI': 0.0094, 'XX': 0.0001, 'XY': 0.0002, 'XZ': 0.0003, 'YI': 0.0188, 'YX': 0.0002, 'YY': 0.0004, 'YZ': 0.0006, 'ZI': 0.028199999999999996, 'ZX': 0.0003, 'ZY': 0.0006, 'ZZ': 0.0009}).  So, to convert from a cirq.AsymmetricDepolarizingChannel object to a stimcirq._two_qubit_asymmetric_depolarize.TwoQubitAsymmetricDepolarizingChannel object, all you need to do is 
```
prob_dict = my_cirq_channel.error_probabilities
del prob_dict["I"*my_cirq_channel.num_qubits()] # Removes probability for the all Identity case
prob_dict = dict(sorted(prob_dict .items())) # just ensures that the dictionary is sorted in the way stim expects. I don't think this is necessary though, as I believe the cirq error_probabilities will always be sorted anyway, but I'm not sure.
stimcirq.TwoQubitAsymmetricDepolarizingChannel(list(prob_dict.values())) # may not even need the list here. Haven't tested.
# You could also build a stim circuit directly from prob_dict.values() here as prob_dict.values() is now outputting the probabilities in the order stim expects (e.g. ['II', 'IX', 'IY', 'IZ','XI', 'XX', 'XY', 'XZ', 'YI', 'YX', 'YY', 'YZ', 'ZI', 'ZX', 'ZY', 'ZZ'])
```

I'm not familiar enough with this codebase to locate where this change should be made, but if you can find where this "ValueError: num_qubits should be 1" error is popping up, you can make the above simple change to draw the error probabilities directly from the cirq.AsymmetricDepolarizingChannel then feed them into whatever function generates the appropriate stim Pauli Channel.
