### ISSUE TITLE
can't delete and insert circuit layer in crumble

### ISSUE THREAD

**Issue by peter-janderks** [quantumlib/Stim#651]
I'm working on a mac and use chrome. I want to delete and insert circuit layers in crumble. If I press crtl+delete or ctrl-insert nothing happens. All other commands I have tried work.

(As a work around, I just open the stim circuit and insert ticks or delete lines).

**Comment by Strilanc** [comment]
Does it work with `command` instead of `ctrl`?

**Comment by peter-janderks** [comment]
No

**Comment by Strilanc** [comment]
I *think* this was resolved in the meantime? Please reopen if this is still happening; but I've definitely seen people on mac on chrome inserting layers.

**Comment by nikojpapa** [comment]
I am also experiencing this. What are the mac commands to insert and delete for this on mac? `command + delete` and `control + delete` does nothing, and there is no explicit `insert` key.

**Comment by nikojpapa** [comment]
For those tech-savvy, you can simulate the combos in the developer's console (right click on page -> Inspect). Go to the "Console" tab and paste the following code:

```
function dispatchKeyCombo(key1, key2) {
  const element = document.querySelector('#cvn');
  const event1 = new KeyboardEvent('keydown', {
    key: key1,
    ctrlKey: true,
    bubbles: true
  });
  element.dispatchEvent(event1);

  const event2 = new KeyboardEvent('keydown', {
    key: key2,
    ctrlKey: true,
    bubbles: true
  });
  element.dispatchEvent(event2);

  const event3 = new KeyboardEvent('keyup', {
    key: key2,
    ctrlKey: true,
    bubbles: true
  });
  element.dispatchEvent(event3);

  const event4 = new KeyboardEvent('keyup', {
    key: key1,
    ctrlKey: true,
    bubbles: true
  });
  element.dispatchEvent(event4);
}
```

You can now dispatch events like `dispatchKeyCombo("Control", "Insert")` for `ctrl+ins` and `dispatchKeyCombo("Control", "Delete")` for `ctrl_del`.
