### ISSUE TITLE
Sinter Custom Sampler

### ISSUE THREAD

**Issue by ghost** [quantumlib/Stim#682]
Similar to how sinter supports custom decoders, it should support custom samplers.

Use cases for this include someone lightly wrapping the flip or tableau simulator, or using a more complex tool like a cirq or numerical simulator to produce the measurement or detector outcomes. 

This should allow people to avoid re-implementing sinter's nice multiprocessing approach to sampling when they want to make a change to how the sampler works.

**Comment by inmzhang** [comment]
Hi, has there been any progress on this issue recently? I have a project coming up that requires a custom sampler. If you currently don't have the time to address it, I would be willing to contribute.
