### ISSUE TITLE
Circuit From QASM method?

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [quantumlib/Stim#686]
I was wondering if there was a method to load a circuit from an openqasm string. I noticed that there's a `Circuit.from_file()` method, but looking at the supported format it didn' t look exactly qasm (but I might be wrong I don't really have that much experience with qasm) or is it?.

**Comment by Strilanc** [comment]
No, there is no such method. There is a method to produce qasm but nothing to parse it. It'd probably take a person-month of work or more to add something like that, given how complicated qasm is.
