### ISSUE TITLE
 Non-CSS code threshold

### ISSUE THREAD

**Issue by mqisnobakht** [quantumlib/Stim#762]
Dear Dr. Gidney,

[Clifford-deformed surface code](https://arxiv.org/abs/2201.07802) is probably an article you have read or heard. Is it possible to use pymatching to determine the threshold for the following code under the desired biased noise?

![image](https://github.com/quantumlib/Stim/assets/95021667/25f83c4c-af95-435a-ae20-ad6286e1847f)

could you please assist me with this?

**Comment by Strilanc** [comment]
As long as it's a surface code, pymatching should be able to decode it.

If you implement these codes as stim circuits and use
pymatching.Matching.from_stim_circuit, you should get a decoder capable of
decoding them.own.

**Comment by Strilanc** [comment]
Closing this because it's not a feature request or bug, just a request for help. Go to the quantum stack exchange for this kind of thing.
