### ISSUE TITLE
add stim.Circuit.without_detectors() and shortest graphlike error crumble output

### ISSUE THREAD

**Issue by Dripto** [quantumlib/Stim#806]
Two quick feature ideas from @mmcewen-g  and I:

1) stim.Circuit.without_detectors(), in case you want to strip them (for crumble or whatever else). Python snippet:

```
det_free_circuit = stim.Circuit()

for instruction in circuit:
    if instruction.name == 'DETECTOR':
        continue
    else:
        det_free_circuit.append(instruction)
```

2) shortest graphlike error  -> crumble
It would be really cool if you could call `shortest_graphlike_error(canonicalize_circuit_errors=True)` and have it output a crumble link that would have that error marked.

**Comment by Strilanc** [comment]
Should without_detectors keep observables?

It's pretty fast to write a loop that strips the detectors out of a circuit, so I'm not sure it's a huge gain over "there's a python API for you to do stuff".

Having to_crumble_url take a list of explained errors or dem errors is interesting.

**Comment by Strilanc** [comment]
Why do you want to remove the detectors? What is it solving? I have good guesses but I want to know.

**Comment by Dripto** [comment]
just because it makes crumble too slow

**Comment by Strilanc** [comment]
That was my first guess.

I think it might make more sense to solve it by making crumble fast. It is currently reparsing the circuit and recomputing all detecting regions everywhere in the circuit every time it draws a frame, and doing that in javascript instead of webassembly.
