### ISSUE TITLE
sinter plot_error_rate plot_args_func doesn't apply to fill_between

### ISSUE THREAD

**Issue by ghost** [quantumlib/Stim#814]
eg when using

```
plot_args_func=lambda index, curve_id: {'color': 'red'
                                                        if curve_id == 'pymatching'
                                                        else 'blue'}
```
the lines are colored according to the decoder, but the fill_betweens are not

**Comment by Strilanc** [comment]
This appears to be fixed now, probably during https://github.com/quantumlib/Stim/commit/e5172a480505fea9bc05ebe506c9bc14cf3d6f2a
