### ISSUE TITLE
CZ gate odd target length error message should print targets

### ISSUE THREAD

**Issue by ghost** [quantumlib/Stim#817]
```
stim.Circuit('CZ')
```

`ValueError: Two qubit gate CZ requires an even number of targets but was given ().`

0 is an even number.

**Comment by Strilanc** [comment]
The given example passes without any error? Also it would be very weird for circuit parsing to mention a python tuple in its error output. Maybe you were calling `circuit.append("CZ")` instead of `circuit.append("CZ", [])`? I can make the former work.

**Comment by mmcewen-g** [comment]
Actually, I think this is a case of me being confused by the error message:
`a=stim.Circuit('CZ')` does work, and so does `a.append('CZ')`

`stim.Circuit('CZ 0')` actually gives the error message above. I guess this is an error message bug?
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 1
----> 1 stim.Circuit('''
      2     CZ 0
      3 ''')

ValueError: Two qubit gate CZ requires an even number of targets but was given ().
```
I had empty CZs in the circuit I was trying to construct, so assumed the message ment that's what it was complaining about.
