### ISSUE TITLE
The results of the detector error model obtained by the DEPOLARIZE2 noise circuit can only be approximated

### ISSUE THREAD

**Issue by kechen666** [quantumlib/Stim#820]
My experimental environment is as follows:
```
python == 3.8
stim == 1.13.0
```

I tried to run the following circuit:
```
import stim
circuit = stim.
    TICK
    DEPOLARIZE2(0.15) 0 1
    TICK
    M 0 1
    DETECTOR rec[-2] 
    DETECTOR rec[-1]
‘‘’)

dem = circuit.detector_error_model()
print(repr(dem))
```
I get the result:
```
stim.DetectorErrorModel(‘’'
    error(0.0417424) D0
    error(0.0417424) D0 D1
    error(0.0417424) D1
‘’')
```
I think there is an anomaly in this result, if D0 indicates whether q0 is flipped or not, and D1 indicates whether q1 is flipped or not. Theoretically, the probability that only D0 flips should be 0.04, the probability that only D1 flips is 0.04, and the probability that both flip is also 0.04.

Why isn't this obtaining an exact value?

**Comment by Strilanc** [comment]
Compute the chance that only D0 fires, given the independent probabilities listed in the detector error model. The D0 error needs to be the only one that happened (0.0417424*(1-0.0417424)*(1-0.0417424)) or the only one that didn't happen ((1-0.0417424)*0.0417424*0.0417424).

```
>>> 0.0417424*(1-0.0417424)*(1-0.0417424) + (1-0.0417424)*0.0417424*0.0417424
0.03999997204224
```
