### ISSUE TITLE
Allow for same task in sinter.collect

### ISSUE THREAD

**Issue by shohamjac** [quantumlib/Stim#842]
Hi,

I have seen in sinter 1.14 you have added a check which throw exception if the same task has been given already:

```python
if key in seen:
     raise ValueError(f'Same task given twice: {self.partial_tasks[k]!r}')
```
located in `_collection_manager.py`.

In my workflow, I run a variety of randomized circuits (as part of erasure simulations) and group them later by the JSON metadata. This sometimes results in the same circuit being added twice, and the current behavior raises an exception.

Would it be possible to change this check to a warning instead of raising an exception? This would allow the process to continue without interruption while still notifying the user of the duplication.

Thanks!

**Comment by Strilanc** [comment]
The reason I added this error is because it's ambiguous what the user wants in this case. Do they want twice as many shots/errors because it's listed twice, or do they want it deduped?

In your case, which do you want to happen?

**Comment by shohamjac** [comment]
In my case, I would like to perform the task twice.

I think a sensible approach might be to run the task as many times as it is listed and return separate `TaskStats` object for each occurrence, which is different from grouping them together as it was in 1.13. If I understood the code correctly it might not be easy to implement since the `strong_id` also used for managing the workers and there is no other distinction between different tasks.

I can work around the issue by assigning each json with a number, but I thought that it might be cleaner without it.

Thanks for considering!
