### ISSUE TITLE
Type error when generating Tableau from conjugated generators

### ISSUE THREAD

**Issue by JLenssen** [quantumlib/Stim#856]
Hi, 

I created a fresh conda environment with Python 3.11.10 on Ubuntu with

```
conda create -n stim python=3.11 pip
conda activate stim
```

After installing the following dependencies:

```
stim~=1.14
numpy~=1.0  # 1.0 instead of 2.0 for pymatching compatibility later
scipy
pymatching
```
with `pip install -r requirements.txt`, I ran into the following type error:

```
import stim

tableau = stim.Tableau.from_conjugated_generators(
  xs=[
    stim.PauliString("+X")
    ],
  xz=[
    stim.PauliString("+Z")
  ]
)
```

Error message:

```
TypeError: from_conjugated_generators(): incompatible function arguments. The following argument types are supported:
    1. (*, xs: List[stim._stim_sse2.PauliString], zs: List[stim._stim_sse2.PauliString]) -> stim._stim_sse2.Tableau

Invoked with: kwargs: xs=[stim.PauliString("+X")], xz=[stim.PauliString("+Z")]
```

Any idea what the issue could be? Missing pybinds?

**Versions:**
- PyMatching         2.2.1
- numpy              1.26.4
- stim               1.14.0

**CPU info**
- Architecture:             x86_64
- CPU op-mode(s):         32-bit, 64-bit
- SSE2 flag listed in `lscpu`

**Comment by Strilanc** [comment]
`xz=[` should be `xs=[`.
